                                                                               
                          
                     
                  
                                                      
                                                                               

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /usr/local/soft/nginx-1.28.0/conf/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    charset utf-8;

    server_tokens off;

    server {
        listen 8082;
        server_name localhost;
        root /sdb1/myprojoct/haoranmusic/song_requests;
        autoindex off;

                                                                      
        location / {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location /payment/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

                                             
        location ^~ /payment/proof/ {
            deny all;
            autoindex off;
            add_header Cache-Control "no-store";
        }

        location ~ \.(mp3|flac|wav|m4a|aac|ogg|wma|ape)$ {
            expires 30d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location ~ \.(mp4|mkv|avi|mov)$ {
            expires 30d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location ~ \.(png|jpg|jpeg|gif|webp|svg)$ {
            expires 30d;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
