spark.master                     spark://192.168.153.131:7077
spark.driver.memory              512m
spark.executor.memory            512m
spark.executor.cores             1
spark.cores.max                  4
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.eventLog.enabled           false
spark.sql.shuffle.partitions     16
spark.pyspark.python             /usr/local/soft/python3.7.16/bin/python3
spark.pyspark.driver.python      /usr/local/soft/python3.7.16/bin/python3
spark.executorEnv.PYTHONPATH     /sdb1/haoranmusicData/python-packages/spark-2.4.8
