import { createApp } from 'vue';
import { createPinia } from 'pinia';
import 'lxgw-wenkai-lite-webfont/lxgwwenkailite-regular.css';
import 'lxgw-wenkai-lite-webfont/lxgwwenkailite-bold.css';
import './styles/index.scss';
import './styles/admin-rift-theme.scss';
import './styles/auth-city-theme.scss';
import './styles/town-daily-theme.scss';
import './styles/feedback.scss';
import App from './App.vue';
import router from './router';
import { configureAuthBackground } from './utils/authBackground';
import { installFeedbackGuards } from './utils/feedbackGuard';
const app = createApp(App);
installFeedbackGuards();
void configureAuthBackground();
app.use(createPinia());
app.use(router);
app.mount('#app');
