












bind 192.168.153.131 127.0.0.1


protected-mode no


port 6379


tcp-backlog 511




daemonize yes


pidfile  /usr/local/soft/redis5.0.14/redis-node1.pid


loglevel notice


logfile /usr/local/soft/redis5.0.14/logs/redis-node1.log


databases 16




dbfilename dump-node1.rdb


dir /usr/local/soft/redis5.0.14/data


save 900 1
save 300 10
save 60 10000


rdbcompression yes


rdbchecksum yes



appendonly yes
appendfilename "appendonly-node1.aof"
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
no-appendfsync-on-rewrite no



maxmemory 2gb
maxmemory-policy allkeys-lru
maxmemory-samples 5
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes



replica-serve-stale-data yes
repl-ping-replica-period 10
repl-timeout 60
repl-disable-tcp-nodelay no
repl-backlog-size 1mb
repl-backlog-ttl 3600



requirepass ${REDIS_PASSWORD}



rename-command KEYS ""
rename-command CONFIG "CONFIG_a8f3k2"

maxclients 10000

timeout 0
tcp-keepalive 300



hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128





latency-monitor-threshold 100
