                     
                                                            
                  
                 

port 26379
daemonize yes
bind 192.168.153.131 127.0.0.1
protected-mode no

pidfile  /usr/local/soft/redis5.0.14/sentinel-node1.pid
logfile  /usr/local/soft/redis5.0.14/logs/sentinel-node1.log
dir /usr/local/soft/redis5.0.14/data/sentinel

sentinel monitor mymaster 192.168.153.131 6379 2
sentinel auth-pass mymaster ${REDIS_PASSWORD}
sentinel down-after-milliseconds mymaster 30000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 180000
sentinel deny-scripts-reconfig yes
