






worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /usr/local/soft/nginx-1.28.0/conf/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    charset utf-8;

    server {
        listen 8081;
        server_name localhost;
        root /sdb1/haoranmusicData/Datas;
        autoindex off;

        location / {
            autoindex off;
            expires 7d;
        }

        location /songs/ {
            autoindex off;
            allow 192.168.153.131;
            allow 127.0.0.1;
            deny all;
            expires 30d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location /mvs/ {
            autoindex off;
            allow 192.168.153.131;
            allow 127.0.0.1;
            deny all;
            expires 30d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location /posts/videos/ {
            autoindex off;
            allow 192.168.153.131;
            allow 127.0.0.1;
            deny all;
            expires 30d;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        }

        location /covers/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
        }

        location /images/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
        }

        location /emojis/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
        }

        location /lyrics/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
        }

        location /decorations/ {
            autoindex off;
            expires 30d;
            add_header Access-Control-Allow-Origin *;
        }

        location /user-content/ {
            autoindex off;
            expires 7d;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
