import type { ExactCount } from '@/utils/exactCount';
export type SongId = string | number;
export type SongActionCommand = 'play-next' | 'view-detail' | 'view-artist' | 'view-album' | 'share';
export interface SongInfo {
    id: SongId;
    title?: string;
    name: string;
    artist?: string;
    artistNames?: string;
    artistIds?: string;
    artistId?: SongId;
    album?: string;
    albumName?: string;
    albumId?: SongId;
    releaseDate?: string;
    releaseTime?: string;
    duration?: number;
    description?: string;
    reason?: string;
    url?: string;
    urlStandard?: string;
    urlHigh?: string;
    urlLossless?: string;
    urlHires?: string;
    urlMaster?: string;
    urlInstrumental?: string;
    blobUrl?: string;
    localPath?: string;
    cover?: string;
    coverUrl?: string;
    lyric?: string;
    lyricUrl?: string;
    mvId?: SongId;
    quality?: string;
    bitrate?: number;
    mainType?: string;
    mainGenre?: string;
    subTypes?: string[];
    versionType?: string | number;
    versionName?: string;
    language?: string;
    source?: string;
    fileType?: string;
    playCount?: ExactCount;
    hotScore?: number;
    commentCount?: ExactCount;
    favoriteCount?: ExactCount;
    downloadCount?: ExactCount;
    avgRating?: number;
    ratingCount?: number;
    isNew?: number | boolean;
    isHot?: number | boolean;
    createTime?: string;
    isFavorite?: boolean;
    isSingle?: boolean;
    allowDownload?: number | boolean;
    allowComment?: number | boolean;
    allowShare?: number | boolean;
    uploaderId?: SongId;
    uploaderType?: number;
    uploaderName?: string;
    isLocal?: boolean;
    filePath?: string;
    fileFormat?: string;
    fileSize?: number;
    sizeStandard?: number;
    sizeHigh?: number;
    sizeLossless?: number;
    resourceType?: number;
    isPreview?: boolean;
}
export interface LocalMusicVO {
    id: SongId;
    title: string;
    name: string;
    artist: string;
    album: string;
    duration: number;
    url: string;
    cover: string;
    filePath: string;
    fileSize: number;
}
