









broker.id=3


listeners=PLAINTEXT://192.168.153.133:9092


advertised.listeners=PLAINTEXT://192.168.153.133:9092




num.network.threads=8


num.io.threads=16


socket.send.buffer.bytes=102400


socket.receive.buffer.bytes=102400


socket.request.max.bytes=104857600


queued.max.requests=500




log.dirs=/sdb1/haoranmusicData/kafka


num.recovery.threads.per.data.dir=4


auto.create.topics.enable=true


log.segment.bytes=1073741824


log.roll.hours=168


log.retention.check.interval.ms=300000


log.cleanup.policy=delete




num.partitions=3


offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=3


default.replication.factor=3


min.insync.replicas=2




log.retention.hours=168


log.retention.bytes=-1




replica.fetch.timeout.ms=30000


replica.fetch.wait.max.ms=500


replica.fetch.min.bytes=1


replica.fetch.max.bytes=1048576


replica.high.watermark.checkpoint.interval.ms=5000


replica.socket.timeout.ms=30000


replica.lag.time.max.ms=60000




zookeeper.connect=192.168.153.131:2181,192.168.153.132:2181,192.168.153.133:2181/kafka


zookeeper.connection.timeout.ms=18000


zookeeper.session.timeout.ms=18000


zookeeper.sync.time.ms=2000




batch.size=16384


linger.ms=5


buffer.memory=33554432


compression.type=lz4




acks=1




session.timeout.ms=30000


heartbeat.interval.ms=3000


enable.auto.commit=true


auto.commit.interval.ms=1000




log.index.size.max.bytes=4194304


log.index.interval.bytes=4096




jmx.port=9999




group.initial.rebalance.delay.ms=3000




delete.topic.enable=true


broker.id=3
listeners=PLAINTEXT://192.168.153.133:9092
advertised.listeners=PLAINTEXT://192.168.153.133:9092
log.dirs=/sdb1/haoranmusicData/kafka
zookeeper.connect=192.168.153.131:2181,192.168.153.132:2181,192.168.153.133:2181/kafka

