export * as userApi from './user';
export * as commentApi from './comment';
export * as listenHistoryApi from './listenHistory';
export * as rankingApi from './ranking';
export * as shareApi from './share';
export * as lyricApi from './lyric';
export * as reportApi from './report';
export * as creditApi from './credit';
export * as withdrawApi from './withdraw';
export * as messageApi from './message';
export * as subscribeApi from './subscribe';
export * as userProfileApi from './userProfile';
export * as emojiApi from './emoji';
export * as emojiShopApi from './emojiShop';
export * as decorationApi from './decoration';
export * as creatorApi from './creator';
export * as adminUserApi from './adminUser';
export * as auditLogApi from './auditLog';
export * as musicTagApi from './musicTag';
export * as badgeApi from './badge';
export * as refundApi from './refund';
export * as lyricRequestApi from './lyricRequest';
export * as moderatorManagementApi from './moderatorManagement';
export * as videoTranscodeApi from './videoTranscode';
export * as feedbackRewardApi from './feedbackReward';
export * as friendApi from './friend';
export * as appealApi from './appeal';
export * as blacklistApi from './blacklist';
export * as creatorAlbumApi from './creatorAlbum';
export * as localMusicApi from './localMusic';
export * as localProxyApi from './localProxy';
export * as multiFileUploadApi from './multiFileUpload';
export * as pushApi from './push';
export * as quickPhraseApi from './quickPhrase';
export * as syncApi from './sync';
export * as userActivityApi from './userActivity';
export * as verifiedApi from './verified';
export * as videoPostApi from './videoPost';
export * as songApi from './song';
export * as recommendApi from './recommend';
export * as searchApi from './search';
export * as playlistApi from './playlist';
export * as albumApi from './album';
export * as artistApi from './artist';
export * as mvApi from './mv';
export * as checkinApi from './checkin';
export * as notificationApi from './notification';
export * as vipApi from './vip';
export * as rewardApi from './reward';
export * as giftApi from './gift';
export * as moderationApi from './moderation';
export * as feedbackApi from './feedback';
export * as statisticsApi from './statistics';
export * as paidResourceApi from './paidResource';
export * as creatorWorkApi from './creatorWork';
export * as playlistSquareApi from './playlistSquare';
export * as musicSquareApi from './musicSquare';
export * as songRatingApi from './songRating';
export * as songDownloadApi from './songDownload';
export * as paymentApi from './payment';
export * as purchasedApi from './purchased';
export * as musicSquareUserApi from './musicSquareUser';
export * as musicSquareWorkApi from './musicSquareWork';
export * as recommendEnhancedApi from './recommendEnhanced';
export * as searchEnhancedApi from './searchEnhanced';
export * as searchHistoryApi from './searchHistory';
export * as songResourceRequestApi from './songResourceRequest';
export * as userWorkApi from './userWork';
export * as favoriteApi from './favorite';
export * as recommendExtendApi from './recommendExtend';
export * as musicSquareExtendApi from './musicSquareExtend';
export type { PageResult, PageResponse, ApiResponse } from './types';
export { login, register, resetPassword, sendVerifyCode, getCaptcha, getCurrentUserInfo, logout } from './user';
export type { UserInfo } from './user';
export type { GiftOrderVO, GiftCreateResult, VipGiftCreateDTO, MarketplaceGiftCreateDTO } from './gift';
export type { SongInfo } from './song';
export type { AlbumSimple, MVSimple, ArtistSimple, PlaylistSimple, UserSimple, SongSimple, HotSearchItem } from './search';
export type { DecorationDTO, UserDecoration } from './decoration';
export type { EmojiPackage } from './emoji';
export type { CreatorInfo, CreatorEarnings, CreatorStats, DecimalAmount } from './creator';
export type { WithdrawRecord } from './withdraw';
